name: deploying
on: push

jobs:
  name:
   runs-on: ubuntu-latest
   steps:
     - name: this will print my name
       run: echo "Hello, ${{ vars.MY_NAME }}"

  build:
   runs-on: ubuntu-latest
   steps:
     - name: this is to build
       run: echo "build"

  Test:
   runs-on: ubuntu-latest
   needs: build
   steps:
     - name: this is to test
       run: echo "test"

  deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
     - name: this is to deploy
       run: echo "deploy"
